### ISSUE TITLE
Write graph templates in YAML

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingaweb2-module-graphite#129]
With a template file like icinga.ini scanning-with-your-eyes is a pain. Let's write them all in YAML:

```ini
[icinga-host-checks.graph]
check_command = "icinga"

[icinga-host-checks.metrics_filters]
active_host_checks.value = "$service_name_template$.perfdata.active_host_checks.value"
passive_host_checks.value = "$service_name_template$.perfdata.passive_host_checks.value"

[icinga-host-checks.urlparams]
title = "Host Checks"
areaAlpha = "0.5"
areaMode = "all"
min = "0"
yUnitSystem = "none"

[icinga-host-checks.functions]
active_host_checks.value = "alias(color($metric$, '#1a7dd7'), 'Active/s')"
passive_host_checks.value = "alias(color($metric$, '#0b3c68'), 'Passive/s')"
```

```yaml
---
icinga-host-checks:
    graph:
        check_command: "icinga"
    metrics_filters:
        active_host_checks.value: "$service_name_template$.perfdata.active_host_checks.value"
        passive_host_checks.value: "$service_name_template$.perfdata.passive_host_checks.value"
    urlparams:
        title: "Host Checks"
        areaAlpha: "0.5"
        areaMode: "all"
        min: "0"
        yUnitSystem: "none"
    functions:
        active_host_checks.value: "alias(color($metric$, '#1a7dd7'), 'Active/s')"
        passive_host_checks.value: "alias(color($metric$, '#0b3c68'), 'Passive/s')"
```

**Comment by Al2Klimov** [comment]
PS: existing templates? 20-lines Perl script! ;)

**Comment by Thomas-Gelf** [comment]
I personally see no value in introducing an additional configuration format.  Especially not when this leads to supporting a mess like YAML. The shown examples do not differ a lot, so to me there is not much gain.

Cheers,
Thomas

NB: I love Perl - but when writing migration utilities in a PHP-based project, PHP should be your the tool of choice ;-) It easily outperforms Perl in most real-world tasks and makes it a lot easier to write maintainable projects. As of today I use Perl only in some very rare use-cases where no libraries with equal feature-set are available for PHP.

**Comment by Al2Klimov** [comment]
1. not "an additional" one, but a replacement – we've no v1.0 yet – so we can break *everything*
2. "value": ["scanning-with-your-eyes"](https://github.com/Icinga/icingaweb2-module-graphite/issues/129#issue-294431938)
3. "mess like YAML": please could you explain?
4. "The shown examples do not differ a lot ...": imagine the whole [icinga.ini](https://github.com/Icinga/icingaweb2-module-graphite/blob/20b87627a98350b55ac7b05ec704cbeea4618fdb/templates/icinga.ini) was migrated
5. "in a PHP-based project, PHP should be your the tool of choice ...": I don't intend to include the script anywhere after I used it once – w/ https://github.com/Icinga/icingaweb2-module-graphite/issues/129#issuecomment-363118034 I just wanted to say: "I won't waste much time while migrating *all* the things"

**Comment by Thomas-Gelf** [comment]
1. Every Icinga Web 2 module uses INI
2. as stated above, in this concrete example the gain is minimal
3. as you love "scrolling with your eyes", just scroll [JSON](https://www.json.org/) and compare it to [YAML](http://yaml.org/spec/1.2/spec.html) - this is completely insane
4. standing by my statement. In addition, I expect all those `.value` settings to be harder to read once cluttering multiple lines in YAML
5. granted. Just wanted to point out that you can easily accomplish the same goal with PHP :)

**Comment by Al2Klimov** [comment]
1. Hello [BP](https://github.com/Icinga/icingaweb2-module-businessprocess)! :wink:
2. So what?
3. Yes, for YAML parser devs – I'm not one of them.

**Comment by Thomas-Gelf** [comment]
1. BP configuration format handled by the businesprocess is a special beast like Icinga Configuration "Format" handled by the director module. It predates Icinga Web 2 and is there for compatibility reasons. Storage backend is modular and we plan to introduce DB-based BP configurations as our future default backend
2. So I'd suggest to reject this feature request
3. This messy spec has an impact when it comes to performance and security. YAML is a serialization and not a configuration format, with all it's consequences. This leads to a sad history of security issues, incompatible parsers, missing bindings and parser devs who gave up.

**Comment by Al2Klimov** [comment]
```ini
[mysql_health-bufferpool_hitrate.graph]
check_command = "mysql_health"

[mysql_health-bufferpool_hitrate.metrics_filters]
value = "$service_name_template$.perfdata.bufferpool_hitrate.value"

[mysql_health-bufferpool_hitrate.urlparams]
areaAlpha = "0.5"
areaMode = "all"
min = "0"
yUnitSystem = "none"

[mysql_health-bufferpool_hitrate.functions]
value = "alias(color($metric$, '#1a7dd7'), 'InnoDB buffer pool hitrate (%)')"


[mysql_health-bufferpool_wait_free.graph]
check_command = "mysql_health"

[mysql_health-bufferpool_wait_free.metrics_filters]
value = "$service_name_template$.perfdata.bufferpool_free_waits_rate.value"

[mysql_health-bufferpool_wait_free.urlparams]
areaAlpha = "0.5"
areaMode = "all"
min = "0"
yUnitSystem = "none"

[mysql_health-bufferpool_wait_free.functions]
value = "alias(color($metric$, '#1a7dd7'), 'InnoDB buffer pool waits/s')"


[mysql_health-clients_aborted.graph]
check_command = "mysql_health"

[mysql_health-clients_aborted.metrics_filters]
value = "$service_name_template$.perfdata.clients_aborted_per_sec.value"

[mysql_health-clients_aborted.urlparams]
areaAlpha = "0.5"
areaMode = "all"
min = "0"
yUnitSystem = "none"

[mysql_health-clients_aborted.functions]
value = "alias(color($metric$, '#1a7dd7'), 'Clients aborted/s')"


[mysql_health-connection_time.graph]
check_command = "mysql_health"

[mysql_health-connection_time.metrics_filters]
value = "$service_name_template$.perfdata.connection_time.value"

[mysql_health-connection_time.urlparams]
areaAlpha = "0.5"
areaMode = "all"
min = "0"
yUnitSystem = "none"

[mysql_health-connection_time.functions]
value = "alias(color(scale($metric$, 1000), '#1a7dd7'), 'Connection time (ms)')"


[mysql_health-connects_aborted.graph]
check_command = "mysql_health"

[mysql_health-connects_aborted.metrics_filters]
value = "$service_name_template$.perfdata.connects_aborted_per_sec.value"

[mysql_health-connects_aborted.urlparams]
areaAlpha = "0.5"
areaMode = "all"
min = "0"
yUnitSystem = "none"

[mysql_health-connects_aborted.functions]
value = "alias(color($metric$, '#1a7dd7'), 'Connects aborted/s')"


[mysql_health-index_usage.graph]
check_command = "mysql_health"

[mysql_health-index_usage.metrics_filters]
value = "$service_name_template$.perfdata.index_usage.value"

[mysql_health-index_usage.urlparams]
areaAlpha = "0.5"
areaMode = "all"
min = "0"
yUnitSystem = "none"

[mysql_health-index_usage.functions]
value = "alias(color($metric$, '#1a7dd7'), 'Index usage (%)')"


[mysql_health-keycache_hitrate.graph]
check_command = "mysql_health"

[mysql_health-keycache_hitrate.metrics_filters]
value = "$service_name_template$.perfdata.keycache_hitrate.value"

[mysql_health-keycache_hitrate.urlparams]
areaAlpha = "0.5"
areaMode = "all"
min = "0"
yUnitSystem = "none"

[mysql_health-keycache_hitrate.functions]
value = "alias(color($metric$, '#1a7dd7'), 'MyISAM keycache hitrate (%)')"


[mysql_health-log_waits.graph]
check_command = "mysql_health"

[mysql_health-log_waits.metrics_filters]
value = "$service_name_template$.perfdata.innodb_log_waits_rate.value"

[mysql_health-log_waits.urlparams]
areaAlpha = "0.5"
areaMode = "all"
min = "0"
yUnitSystem = "none"

[mysql_health-log_waits.functions]
value = "alias(color($metric$, '#1a7dd7'), 'InnoDB log waits/s')"


[mysql_health-long_running_procs.graph]
check_command = "mysql_health"

[mysql_health-long_running_procs.metrics_filters]
value = "$service_name_template$.perfdata.long_running_procs.value"

[mysql_health-long_running_procs.urlparams]
areaAlpha = "0.5"
areaMode = "all"
min = "0"
yUnitSystem = "none"

[mysql_health-long_running_procs.functions]
value = "alias(color($metric$, '#1a7dd7'), 'Long running processes')"


[mysql_health-open_files.graph]
check_command = "mysql_health"

[mysql_health-open_files.metrics_filters]
value = "$service_name_template$.perfdata.open_files.value"

[mysql_health-open_files.urlparams]
areaAlpha = "0.5"
areaMode = "all"
min = "0"
yUnitSystem = "none"

[mysql_health-open_files.functions]
value = "alias(color($metric$, '#1a7dd7'), 'Open files')"


[mysql_health-qcache_hitrate.graph]
check_command = "mysql_health"

[mysql_health-qcache_hitrate.metrics_filters]
value = "$service_name_template$.perfdata.qcache_hitrate.value"

[mysql_health-qcache_hitrate.urlparams]
areaAlpha = "0.5"
areaMode = "all"
min = "0"
yUnitSystem = "none"

[mysql_health-qcache_hitrate.functions]
value = "alias(color($metric$, '#1a7dd7'), 'Query cache hitrate (%)')"


[mysql_health-qcache_hitrate-selects_per_sec.graph]
check_command = "mysql_health"

[mysql_health-qcache_hitrate-selects_per_sec.metrics_filters]
value = "$service_name_template$.perfdata.selects_per_sec.value"

[mysql_health-qcache_hitrate-selects_per_sec.urlparams]
areaAlpha = "0.5"
areaMode = "all"
min = "0"
yUnitSystem = "none"

[mysql_health-qcache_hitrate-selects_per_sec.functions]
value = "alias(color($metric$, '#1a7dd7'), 'Selects/s')"


[mysql_health-qcache_lowmem_prunes.graph]
check_command = "mysql_health"

[mysql_health-qcache_lowmem_prunes.metrics_filters]
value = "$service_name_template$.perfdata.qcache_lowmem_prunes_rate.value"

[mysql_health-qcache_lowmem_prunes.urlparams]
areaAlpha = "0.5"
areaMode = "all"
min = "0"
yUnitSystem = "none"

[mysql_health-qcache_lowmem_prunes.functions]
value = "alias(color($metric$, '#1a7dd7'), 'Query cache lowmem prunes/s')"


[mysql_health-slow_queries.graph]
check_command = "mysql_health"

[mysql_health-slow_queries.metrics_filters]
value = "$service_name_template$.perfdata.slow_queries_rate.value"

[mysql_health-slow_queries.urlparams]
areaAlpha = "0.5"
areaMode = "all"
min = "0"
yUnitSystem = "none"

[mysql_health-slow_queries.functions]
value = "alias(color($metric$, '#1a7dd7'), 'Slow queries/s')"
```

vs.

```yaml
---
mysql_health-bufferpool_hitrate:
    graph:
        check_command: "mysql_health"
    metrics_filters:
        value: "$service_name_template$.perfdata.bufferpool_hitrate.value"
    urlparams: &urlparams
        areaAlpha: 0.5
        areaMode: "all"
        min: 0
        yUnitSystem: "none"
    functions:
        value: "alias(color($metric$, '#1a7dd7'), 'InnoDB buffer pool hitrate (%)')"

mysql_health-bufferpool_wait_free:
    graph:
        check_command: "mysql_health"
    metrics_filters:
        value: "$service_name_template$.perfdata.bufferpool_free_waits_rate.value"
    urlparams: *urlparams
    functions:
        value: "alias(color($metric$, '#1a7dd7'), 'InnoDB buffer pool waits/s')"

mysql_health-clients_aborted:
    graph:
        check_command: "mysql_health"
    metrics_filters:
        value: "$service_name_template$.perfdata.clients_aborted_per_sec.value"
    urlparams: *urlparams
    functions:
        value: "alias(color($metric$, '#1a7dd7'), 'Clients aborted/s')"

mysql_health-connection_time:
    graph:
        check_command: "mysql_health"
    metrics_filters:
        value: "$service_name_template$.perfdata.connection_time.value"
    urlparams: *urlparams
    functions:
        value: "alias(color(scale($metric$, 1000), '#1a7dd7'), 'Connection time (ms)')"

mysql_health-connects_aborted:
    graph:
        check_command: "mysql_health"
    metrics_filters:
        value: "$service_name_template$.perfdata.connects_aborted_per_sec.value"
    urlparams: *urlparams
    functions:
        value: "alias(color($metric$, '#1a7dd7'), 'Connects aborted/s')"

mysql_health-index_usage:
    graph:
        check_command: "mysql_health"
    metrics_filters:
        value: "$service_name_template$.perfdata.index_usage.value"
    urlparams: *urlparams
    functions:
        value: "alias(color($metric$, '#1a7dd7'), 'Index usage (%)')"

mysql_health-keycache_hitrate:
    graph:
        check_command: "mysql_health"
    metrics_filters:
        value: "$service_name_template$.perfdata.keycache_hitrate.value"
    urlparams: *urlparams
    functions:
        value: "alias(color($metric$, '#1a7dd7'), 'MyISAM keycache hitrate (%)')"

mysql_health-log_waits:
    graph:
        check_command: "mysql_health"
    metrics_filters:
        value: "$service_name_template$.perfdata.innodb_log_waits_rate.value"
    urlparams: *urlparams
    functions:
        value: "alias(color($metric$, '#1a7dd7'), 'InnoDB log waits/s')"

mysql_health-long_running_procs:
    graph:
        check_command: "mysql_health"
    metrics_filters:
        value: "$service_name_template$.perfdata.long_running_procs.value"
    urlparams: *urlparams
    functions:
        value: "alias(color($metric$, '#1a7dd7'), 'Long running processes')"

mysql_health-open_files:
    graph:
        check_command: "mysql_health"
    metrics_filters:
        value: "$service_name_template$.perfdata.open_files.value"
    urlparams: *urlparams
    functions:
        value: "alias(color($metric$, '#1a7dd7'), 'Open files')"

mysql_health-qcache_hitrate:
    graph:
        check_command: "mysql_health"
    metrics_filters:
        value: "$service_name_template$.perfdata.qcache_hitrate.value"
    urlparams: *urlparams
    functions:
        value: "alias(color($metric$, '#1a7dd7'), 'Query cache hitrate (%)')"

mysql_health-qcache_hitrate-selects_per_sec:
    graph:
        check_command: "mysql_health"
    metrics_filters:
        value: "$service_name_template$.perfdata.selects_per_sec.value"
    urlparams: *urlparams
    functions:
        value: "alias(color($metric$, '#1a7dd7'), 'Selects/s')"

mysql_health-qcache_lowmem_prunes:
    graph:
        check_command: "mysql_health"
    metrics_filters:
        value: "$service_name_template$.perfdata.qcache_lowmem_prunes_rate.value"
    urlparams: *urlparams
    functions:
        value: "alias(color($metric$, '#1a7dd7'), 'Query cache lowmem prunes/s')"

mysql_health-slow_queries:
    graph:
        check_command: "mysql_health"
    metrics_filters:
        value: "$service_name_template$.perfdata.slow_queries_rate.value"
    urlparams: *urlparams
    functions:
        value: "alias(color($metric$, '#1a7dd7'), 'Slow queries/s')"
```
